import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderNav from './ui/header_nav'
import Footer from './ui/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Inmech2',
    default: 'Inmech2',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  
}: {
  children: React.ReactNode,
 
}) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <div className='appCont'>
          <HeaderNav />
          <main className='main'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
    
  )
}
